SUPABASE_DB_URL = "postgresql://postgres.yjjlpjzawwymxymreuum:UnitCircle42%21@aws-0-us-west-2.pooler.supabase.com:6543/postgres"

RAPIDAPI_KEY = "469dd8cd83mshc40197bf611fbbbp1203e0jsne94a23559b4b"

auth_key = "f8d93kD92kLm2Pp1x9Z!@#8fjsl"