SUPABASE_DB_URL = "postgresql://postgres:UnitCircle42%21@db.yjjlpjzawwymxymreuum.supabase.co:5432/postgres"

RAPIDAPI_KEY = "469dd8cd83mshc40197bf611fbbbp1203e0jsne94a23559b4b"

auth_key = "f8d93kD92kLm2Pp1x9Z!@#8fjsl"